### PR TITLE
Add the dates and location for SoCraTes BE 2016.

### PR DESCRIPTION
**Pull request by SamirTalwar**

### CODE REVIEW

**Comment by NicoleRauch** [comment]
Hey, that was quick! Thanks :-)

I'd actually prefer to have the conferences in chronological order, though: This year, FR is later and BE is earlier, so they swapped.

**Comment by SamirTalwar** [comment]
Done. 😄

**Comment by NicoleRauch** [comment]
Deployed and live :-)

**Comment by SamirTalwar** [comment]
Cheers!

**Pull request merged**
