### PR TITLE
Update SoCraTes twitter stuff

### PR DESCRIPTION
**Pull request by UrsMetz**
The twitter handle and the date in the tweet template were out-of-date.

### CODE REVIEW

**Comment by UrsMetz** [comment]
oh.. I should have better run the tests before pushing the last commit ;-). Will fix this.

**Comment by leider** [comment]
Hi Urs,
I propose to

- change the puglint settings, and
- extract all the volatile text parts like date, hashtag to make changes easier for next year
- great would be to have them in an extra file, maybe an object twitterConstants {hashtag: 'tag', etc.}

**Comment by UrsMetz** [comment]
Hi Andreas,

all right, I will work on that, but it might take a bit longer, so don't expect to have it by today :-).
Should this be done in this pull request?

**Comment by leider** [comment]
No, not obligatory. Fix this one and then open a new one. :)

**Comment by UrsMetz** [comment]
Okay, I pushed another commit to replace the template string with plain old string concatenation.
I will open a new pull request for the configurable twitter data.

**Pull request merged**
