### PR TITLE
introduced this year's gdcr and 2018 events

### PR DESCRIPTION
**Pull request by leider**
- also updated uglify for faster conversion

### CODE REVIEW

**Comment by NicoleRauch** [comment]
I'm deploying right now

**Comment by NicoleRauch** [comment]
I think we used to have a link on the main page, didn't we? Would you like to add that one as well?

**Comment by leider** [comment]
Was genau?

**Comment by leider** [comment]
Weiß was du meinst

**Comment by leider** [comment]
Kommt gleich

**Comment by leider** [comment]
durchgepusht

**Pull request merged**
