### PR TITLE
[wip] Add docker files

### PR DESCRIPTION
**Pull request by webwurst**
Some tests are failing.

### CODE REVIEW

**Comment by webwurst** [comment]
Tree tests are failing:
```
․․․․․․․․․․․!․․․․․․․․․!!․

21 passing (2s)
3 failing

1) Activity application with DB - on submit - rejects an activity if there is a race condition on save:
   Error: expected 302 "Found", got 500 "Internal Server Error"
    at Test._assertStatus (node_modules/supertest/lib/test.js:250:12)
    at Test._assertFunction (node_modules/supertest/lib/test.js:265:11)
    at Test.assert (node_modules/supertest/lib/test.js:153:18)
    at Server.assert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1549:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

2) Members application with DB getMembersWithInterest does not find a member by partial matches of an interest:
   Uncaught TypeError: Cannot read property 'length' of undefined
    at Must.exports.length (node_modules/must-dist/lib/assertions.js:677:32)
    at softwerkskammer/testWithDB/membersDB/members_queries_test.js:57:33
    at toMemberList (softwerkskammer/lib/members/memberstore.js:9:1530)
    at apply (node_modules/lodash/lodash.js:481:27)
    at wrapper (node_modules/lodash/lodash.js:5156:16)
    at softwerkskammer/lib/persistence/persistence.js:9:3647
    at handleCallback (node_modules/mongodb/lib/utils.js:96:12)
    at node_modules/mongodb/lib/cursor.js:855:22
    at handleCallback (node_modules/mongodb-core/lib/cursor.js:156:5)
    at node_modules/mongodb-core/lib/cursor.js:604:24
    at queryCallback (node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:185:20)
    at node_modules/mongodb-core/lib/connection/pool.js:428:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

3) Members application with DB getMembersWithInterest does not find a member when searching case sensitive:
   Uncaught TypeError: Cannot read property 'length' of undefined
    at Must.exports.length (node_modules/must-dist/lib/assertions.js:677:32)
    at softwerkskammer/testWithDB/membersDB/members_queries_test.js:64:33
    at toMemberList (softwerkskammer/lib/members/memberstore.js:9:1530)
    at apply (node_modules/lodash/lodash.js:481:27)
    at wrapper (node_modules/lodash/lodash.js:5156:16)
    at softwerkskammer/lib/persistence/persistence.js:9:3647
    at handleCallback (node_modules/mongodb/lib/utils.js:96:12)
    at node_modules/mongodb/lib/cursor.js:855:22
    at handleCallback (node_modules/mongodb-core/lib/cursor.js:156:5)
    at node_modules/mongodb-core/lib/cursor.js:604:24
    at queryCallback (node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:185:20)
    at node_modules/mongodb-core/lib/connection/pool.js:428:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

/ping @andreassimon @rradczewski

**Comment by NicoleRauch** [comment]
Sorry - but - why?

**Comment by andreassimon** [comment]
Only happens with Docker?

**Comment by leider** [comment]
Please state intention and value for this PR.

**Comment by leider** [comment]
@webwurst is this still an issue? - Otherwise I'll close it.

**Comment by webwurst** [comment]
This provides a container setup for local development. Uses less resources than a virtual machine and you can just bind mount your development directory into the container. If there's no need for this feel free to close :)

**Comment by leider** [comment]
Closing this because the main committers develop on "real" machines, the production environment does not provide docker and new stuff needs to be maintained. Maintenance is the main reason for not integrating such an environment.
Thanks for understanding

**Comment by webwurst** [comment]
@leider totally fine! :+1:

**Pull request closed without merging**
