### PR TITLE
test(testWithDB): fix mocha_istanbul:testWithDB fails on MongoDB v3.2.9

### PR DESCRIPTION
**Pull request by coderbyheart**
This fixes softwerkskammer/Agora#1105

### CODE REVIEW

**Comment by NicoleRauch** [comment]
Interesting! Can you please provide an explicit test for this, as the tests that fail on your DB don't fail on mine (which is v 2.4.1)?

**Comment by leider** [comment]
Maybe the tests failed because no example data available in mongo?

**Comment by NicoleRauch** [comment]
Then it would definitely be good to have an explicit test for this case...

**Comment by coderbyheart** [comment]
Ok, I'm currently trying to make the travis build run on mongo2 and mongo3 to show the error

**Comment by coderbyheart** [comment]
@NicoleRauch I've squashed the commits into two, you can see that the first one fails and that the second one after the fix passes: https://github.com/softwerkskammer/Agora/pull/1106/commits

**Comment by leider** [comment]
Many thanks. Sometimes it's new version that reveal previous usage bugs.

**Pull request merged**
