### PR TITLE
Update texts, logo and partner conferences to 2017

### PR DESCRIPTION
**Pull request by pas2al**

### CODE REVIEW

**Comment by NicoleRauch** [comment]
Thanks, looks very good to me! (especially the updated conferences, good work!)

The only thing I don't like too much are the linebreaks in the img tags - is there a good reason not to keep the img tags on one line?

**Comment by NicoleRauch** [comment]
Oh, and do you also want to adapt the code where necessary? (AFAIK this should only require a change in activities/socratesConstants.js but this needs running the tests and manually double-checking the app).

[Note: "No" or "Not yet" are valid answers :-) ]

**Comment by pas2al** [comment]
Regarding the line breaks...there no reason, was just an automatic linebreak while typing.

**Comment by pas2al** [comment]
And the answers to the second questions is not yet :-) The main reason for now is, that some tests are failing in general and i need to fix that first before changing the code (besides some static changes like test and logos)

**Comment by NicoleRauch** [comment]
Fair enough :-)

**Comment by pas2al** [comment]
Hehe, nice ;-)

**Pull request merged**
